### ISSUE TITLE
トッピングに豚しゃぶがない

### ISSUE THREAD

**Issue by blogath** [einst-alfimi/CurryPriceCalculator#8]
仕様だったらすいません

**Comment by blogath** [comment]
https://www.ichibanya.co.jp/menu/topping.html
肉類のトッピング

**Comment by einst-alfimi** [comment]
対応しました 952f84e6d7a8fc6f5493d6165a045a7ce60df957

**Comment by einst-alfimi** [comment]
チキンにこみ、フライドチキン、ハンバーグ、豚しゃぶ、メンチカツ　が抜けていたので追加
